### ISSUE TITLE
Error in check mode using upgrade:yes

### ISSUE THREAD

**Issue by ellton101** [kewlfft/ansible-aur#42]
with this playbook:

---
- hosts: localhost
  tasks:
    - name: Update archlinux
      aur:
        upgrade: yes
        state: latest

I get this error in check mode (ansible-playbook -C):

The full traceback is:
Traceback (most recent call last):
  File "/home/ellton/.ansible/tmp/ansible-tmp-1591791499.424747-1888790-158389577016436/AnsiballZ_aur.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ellton/.ansible/tmp/ansible-tmp-1591791499.424747-1888790-158389577016436/AnsiballZ_aur.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ellton/.ansible/tmp/ansible-tmp-1591791499.424747-1888790-158389577016436/AnsiballZ_aur.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.aur', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_aur_payload_vovp83ji/ansible_aur_payload.zip/ansible/modules/aur.py", line 313, in <module>
  File "/tmp/ansible_aur_payload_vovp83ji/ansible_aur_payload.zip/ansible/modules/aur.py", line 309, in main
  File "/tmp/ansible_aur_payload_vovp83ji/ansible_aur_payload.zip/ansible/modules/aur.py", line 300, in apply_module
  File "/tmp/ansible_aur_payload_vovp83ji/ansible_aur_payload.zip/ansible/modules/aur.py", line 126, in check_packages
TypeError: 'NoneType' object is not iterable
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ellton/.ansible/tmp/ansible-tmp-1591791499.424747-1888790-158389577016436/AnsiballZ_aur.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/hom
e/ellton/.ansible/tmp/ansible-tmp-1591791499.424747-1888790-158389577016436/AnsiballZ_aur.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ellton/.ansible/tmp/ansibl
e-tmp-1591791499.424747-1888790-158389577016436/AnsiballZ_aur.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.aur', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/pyt
hon3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globa
ls,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aur_payload_vovp83ji/ansible_aur_payload.zip/ansible/modules/aur.py\", line 313, in <module>\n  File \"/tmp
/ansible_aur_payload_vovp83ji/ansible_aur_payload.zip/ansible/modules/aur.py\", line 309, in main\n  File \"/tmp/ansible_aur_payload_vovp83ji/ansible_aur_payload.zip/ansible/modules/aur.py\", line 300, in apply_module\n  File 
\"/tmp/ansible_aur_payload_vovp83ji/ansible_aur_payload.zip/ansible/modules/aur.py\", line 126, in check_packages\nTypeError: 'NoneType' object is not iterable\n",                                                              
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by kewlfft** [comment]
see   c2fd7b3

**Comment by ellton101** [comment]
It is working! TY
